import { Inter } from "next/font/google";
import "../../globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hokrex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Mainstatestore>
          <Navbar cart={true} />
          {children}
        </Mainstatestore>
      </body>
    </html>
  );
}
