import { Inter } from "next/font/google";
import "../../globals.css";
import Mainstatestore from "@/components/Mainstate(store)/Mainstatestore";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hokrex - Account",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_CLIENT_ID}>
        <Mainstatestore>
          <body className={inter.className}>{children}</body>
        </Mainstatestore>
      </GoogleOAuthProvider>
    </html>
  );
}
