import { Inter } from "next/font/google";
import "../../globals.css";
import Mainstatecart from "@/components/Mainstate(cart)/Mainstatecart";
import Mainstatestore from "@/components/Mainstate(store)/Mainstatestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hokrex - Checkout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Mainstatestore> */}
        <Mainstatecart>{children}</Mainstatecart>
        {/* </Mainstatestore> */}
      </body>
    </html>
  );
}
